---
kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm test
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: ./release.tar.gz
    when:
      event: tag
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: test-ci-romain
      username: drone-CI
