---
kind: pipeline
name: react-ci-cd

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm test
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: test-ci-romain
      username: drone-CI
